CREATE TABLE books (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title TEXT NOT NULL,
  author TEXT,
  cover_base64 TEXT,
  file_path TEXT,
  total_pages INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE book_chapters (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  order_index INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE book_sentences (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  chapter_id INTEGER NOT NULL REFERENCES book_chapters(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  order_in_chapter INTEGER NOT NULL,
  page_number INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE reading_positions (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE UNIQUE,
  page_number INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);
